////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/).

SPDX-License-Identifier: CC-BY-4.0


////
= Part 1: Metamodel (IDTA-01001)


.Overview Metamodel of the Asset Administration Shell
[plantuml, 11-asset-administration-shell, svg]
....

@startuml

!include partial$diagrams/classes/asset-administration-shell.puml
!include partial$diagrams/classes/asset-information.puml
!include partial$diagrams/classes/enum-asset-kind.puml
!include partial$diagrams/classes/specific-asset-id.puml
!include partial$diagrams/classes/submodel.puml
!include partial$diagrams/classes/qualifier.puml
!include partial$diagrams/classes/submodel-element.puml
!include partial$diagrams/classes/property.puml

AssetAdministrationShell ..> AssetInformation
AssetAdministrationShell -->"submodel 0..*" Submodel :Reference
AssetAdministrationShell -->"derivedFrom\n0..1" AssetAdministrationShell :Reference
AssetInformation ..> AssetKind
AssetInformation ..> SpecificAssetId
Submodel ..> SubmodelElement
Submodel ..> Qualifier
SubmodelElement .> Qualifier
SubmodelElement <|-- Property
SubmodelElement ..> PropertyDefinition : <<external global reference>>
@enduml
....
